import { useState } from 'react'
import type { Campaign, Lang, AssetKey } from '../types/campaign'
import { STRATEGIES } from '../data/council'
import { Catto } from './Catto'

interface ResultSectionProps {
  campaign: Campaign
  photoUrl: string | null
  source: 'live' | 'mock'
}

const TABS: [AssetKey, string][] = [
  ['ig', '📷 Instagram'],
  ['google', '🔍 Google'],
  ['sign', '🪧 Counter sign'],
  ['script', '🎭 Staff script'],
  ['plan', '⏱ 20-min plan'],
]

const TAB_LABELS: Record<AssetKey, string> = {
  ig: 'Instagram caption',
  google: 'Google business post',
  sign: 'Counter sign',
  script: 'Staff script',
  plan: '20-minute execution plan',
}

export function ResultSection({ campaign: c, photoUrl, source }: ResultSectionProps) {
  const [tab, setTab] = useState<AssetKey>('ig')
  const [lang, setLang] = useState<Lang>('en')
  const [copied, setCopied] = useState(false)

  const A = c.assets

  const copy = (text: string) => {
    try {
      navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch {
      /* clipboard API unavailable */
    }
  }

  const langClass = lang === 'zh' ? 'lang-zh' : lang === 'ko' ? 'lang-ko' : ''

  return (
    <div className="cc-result">
      <div className="cc-result-head">
        <span className="badge">RESULT {source === 'live' ? '· LIVE AI' : '· DEMO'}</span>
        <h2 style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          Today's Play
          <Catto scale={1.6} state="cheering" withSign />
        </h2>
      </div>

      {c.visionRead && (
        <div className="cc-card cc-vision">
          {photoUrl ? (
            <img src={photoUrl} alt="Product" />
          ) : (
            <div
              style={{
                width: 120,
                height: 120,
                borderRadius: 12,
                background: 'linear-gradient(135deg, rgba(255,107,157,.18), rgba(245,200,66,.18))',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: 48,
              }}
            >
              📸
            </div>
          )}
          <div className="v-text">
            <div className="cc-eyebrow">👁️ AI Vision · {source === 'live' ? 'analyzed your photo' : 'sample read'}</div>
            <strong>{c.visionRead}</strong>
            <em>
              {source === 'live'
                ? 'Generated by Claude Sonnet 4 multimodal vision'
                : 'Sample data — upload a photo and switch to Live AI for real vision analysis'}
            </em>
          </div>
        </div>
      )}

      <div className="cc-revenue">
        <div className="cc-revenue-l">
          <div className="r-eyebrow">EST. EXTRA REVENUE · TODAY</div>
          <div className="r-num">+${c.revenue}</div>
          <div className="r-orders">+{c.orders} orders @ ${c.avg} avg</div>
          <div className="r-title">{c.name}</div>
        </div>
        <div className="cc-revenue-r">
          <div className="cc-score">
            <div className="s-eyebrow">Opportunity Score</div>
            <div className="s-row">
              <b>{c.score}</b>
              <span>/ 100</span>
            </div>
            <div className="s-bar">
              <i style={{ width: c.score + '%' }} />
            </div>
          </div>
          <div className="cc-window">
            <div className="w-eyebrow">⏰ Time window</div>
            <strong>{c.windowText}</strong>
          </div>
        </div>
      </div>

      <div>
        <div className="cc-eyebrow" style={{ margin: '4px 4px 12px' }}>Strategy options · Catto picked one</div>
        <div className="cc-strategies">
          {STRATEGIES.map((s) => (
            <div key={s.id} className={`cc-strategy ${c.chosen === s.id ? 'is-chosen' : ''}`}>
              <div className="icon">{s.emoji}</div>
              <h4>{s.name}</h4>
              <p>{s.desc}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="cc-card cc-campaign">
        <div className="c-eyebrow">CAMPAIGN</div>
        <h3>{c.name}</h3>
        <p className="c-tag">{c.tag}</p>
        <hr className="c-divider" />
        <div className="c-grid">
          <div>
            <h5>◈ The offer</h5>
            <p>{c.offer}</p>
          </div>
          <div>
            <h5>◐ Why this wins</h5>
            <p>{c.why}</p>
          </div>
        </div>
      </div>

      <div className="cc-card cc-signals">
        <div className="cc-eyebrow" style={{ marginBottom: 12 }}>
          Signal analysis · 5 inputs → 1 play
        </div>
        {c.signals.map((row, i) => (
          <div key={i} className="row">
            <div className="idx">{String(i + 1).padStart(2, '0')}</div>
            <b>{row.name}</b>
            <span>{row.impact}</span>
          </div>
        ))}
      </div>

      <div className="cc-card cc-assets">
        <div className="cc-asset-bar">
          <div className="cc-asset-tabs">
            {TABS.map(([id, label]) => (
              <button key={id} className={tab === id ? 'is-active' : ''} onClick={() => setTab(id)}>
                {label}
              </button>
            ))}
          </div>
          <div className="cc-lang">
            {(['en', 'zh', 'ko'] as Lang[]).map((l) => (
              <button key={l} className={lang === l ? 'is-active' : ''} onClick={() => setLang(l)}>
                {l === 'en' ? 'EN' : l === 'zh' ? '中文' : '한국어'}
              </button>
            ))}
          </div>
        </div>
        <div className="cc-asset-body">
          <div className="cc-asset-eyebrow">
            <span>◉ {TAB_LABELS[tab]}</span>
            {tab !== 'sign' && tab !== 'plan' && (
              <button
                className={`copy-btn ${copied ? 'copied' : ''}`}
                onClick={() => {
                  const t =
                    tab === 'ig'
                      ? A.ig[lang]
                      : tab === 'google'
                        ? A.google[lang]
                        : tab === 'script'
                          ? A.script[lang]
                          : ''
                  copy(t)
                }}
              >
                {copied ? '✓ Copied' : 'Copy'}
              </button>
            )}
          </div>

          {tab === 'ig' && (
            <div className={`cc-asset-content is-ig ${langClass}`}>
              <div className="cc-ig-thumb">🍵</div>
              <div className="cc-ig-body">{A.ig[lang]}</div>
            </div>
          )}

          {tab === 'google' && <div className={`cc-asset-content ${langClass}`}>{A.google[lang]}</div>}

          {tab === 'sign' && (
            <div className={`cc-asset-content is-sign ${langClass}`}>
              <div className="sign-big">{A.sign[lang].big}</div>
              <div className="sign-sub">{A.sign[lang].sub}</div>
            </div>
          )}

          {tab === 'script' && <div className={`cc-asset-content is-script ${langClass}`}>{A.script[lang]}</div>}

          {tab === 'plan' && (
            <div className={`cc-asset-content is-plan ${langClass}`}>
              <ol>
                {A.plan[lang].map((step, i) => (
                  <li key={i}>{step}</li>
                ))}
              </ol>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
